### ISSUE TITLE
xDnsServerAddress (IPv6) fails with Property NameServer does not exist

### ISSUE THREAD

**Issue by roneystein** [PowerShell/xNetworking#237] opened 2017-07-25 17:53 UTC
In an IPv6 interface, after disabling DHCP and configuring the interface address, attempting to configure DNS server address results in:

"Property NameServer does not exist at path HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\Interfaces\{#interface#}\."

Where #interface# is the interface identifier.

```
Configuration IPv6Dnsserver
{
    Import-DscResource -Module xNetworking
    Node 'localhost'
    {
        xDnsServerAddress IPv6DnsServer
        {
            Address        = '#ipaddress#'
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv6'
            Validate       = $false
        }
    }
}
```
With #ipaddress# being the DNS Server IPv6.
Worked fine on version 4.0.
OS is Windows 10.

**Comment by PlagueHO** [comment] 2017-07-26 07:37
Hi @roneystein - I've identified the cause of the problem I think and should be able to fix it. I'll submit a PR today or tomorrow to get this fixed and it should go in before the next release.

Thanks for submitting this.

FYI: It is caused if the NameServer property does not exist for an interface in the registry. This error should have been suppressed but the `Get-ItemPropertyValue` cmdlet ignores the `-ErrorAction SilentlyContinue` parameter.

**Comment by PlagueHO** [comment] 2017-07-26 08:10
@roneystein - I've submitted a PR for this and should get it merged over the next few days (depending on how busy the other maintainers are). Thanks again!

**Comment by roneystein** [comment] 2017-07-26 21:34
@PlagueHO thanks for the feedback

**Comment by PlagueHO** [comment] 2017-07-27 00:11
@roneystein - no worries!

**Closed** 2017-07-28 21:25 UTC
Labels: bug, help wanted
