### ISSUE TITLE
xFirewall RemoteAddress fails test if CIDR notation is used.

### ISSUE THREAD

**Issue by dm3942** [PowerShell/xNetworking#169] opened 2016-12-13 07:55 UTC
xNetworking version 3.0.0.0
RemoteAddress test fails if CIDR notation is used in the configuration. The rule is created, but the test fails.

Recommendations: 
1.  Update documentation providing only currently supported formats.
2.  Provide an example.
3.  Provide intellisense option showing a subnet mask notation. 
4.  Update code to translate CIDR notation to subnet mask.

----- This firewall will get created successfully but the test will FAIL.
        xFirewall myNagiosFw
        {
            Name  = "DSC-Nagios"
            Enabled = $true
            Action = 'Allow'
            LocalPort = 5666
            Direction = 'Inbound'
            Protocol = 'TCP'
            Ensure = 'Present'
            RemoteAddress = '10.10.0.0/16' # CAUSE OF TEST FAILURE
        }

----- This firewall will get created successfully and the test will PASS.
        xFirewall myNagiosFw
        {
            Name  = "DSC-Nagios"
            Enabled = $true
            Action = 'Allow'
            LocalPort = 5666
            Direction = 'Inbound'
            Protocol = 'TCP'
            Ensure = 'Present'
            RemoteAddress = '10.10.0.0/255.255.0.0' # CAUSE OF TEST FAILURE
        }

We managed to inject some verbose statements into the function Test-RuleProperties
File: C:\Program Files\WindowsPowerShell\Modules\xNetworking\3.0.0.0\DSCResources\MSFT_xFirewall\MSFT_xFirewall.psm1
... code added ....
Write-Verbose "array-----:$ParameterSource----:$ParameterNew -----"
.... output from code .... 
VERBOSE: [localhost]:  [[xFirewall]myNagiosFw] Test-RuleProperties: RemoteAddress property value '10.10.0.0/255.255.0.0' does not match desired state '10.10.0.0/16'.

**Comment by PlagueHO** [comment] 2016-12-13 09:25
Thanks for logging this @dm3942 

This is expected behavior because the *-NetFirewallAddressFilter cmdlets always returns the address with a netmask rather than in CIDR notation.

It should be possible to to adjust the test in Test-RuleProperties to do a comparison with both the CIDR notation and the netmask.

I'll try and get to this when I can unless someone else gets to this first.

**Comment by PlagueHO** [comment] 2016-12-24 01:44
@dm3942 - I'll look at this problem this week.

**Comment by PlagueHO** [comment] 2016-12-26 07:58
@dm3942 - I've submitted a fix for this issue in the above PR. Might take a little while to get merged because it is not an insignificant change.

**Comment by dm3942** [comment] 2017-01-03 07:18
No problem. Thanks for considering it.

________________________________

**Comment by PlagueHO** [comment] 2017-01-07 03:35
@dm3942 - a pleasure doing it. I'm just waiting on my PR to be reviewed so the change can go in.

@tysonjhayes - any chance you might have some time at some point to check over #173 for me - no problems if not sir, I can hassle some of the others a bit :grin: ? I realize it's a bit of a bit large PR because of it includes a bunch of work towards making xNetworking HQRM.

**Closed** 2017-01-15 06:52 UTC
Labels: bug, in progress
