### ISSUE TITLE
Built-in firewall rules isn't found

### ISSUE THREAD

**Issue by Identitry** [PowerShell/xNetworking#75] opened 2015-12-25 17:49 UTC
Running this for enabling the built in RDP firewall rules...

        # Enable Firewall Rule 'Remote Desktop - Shadow (TCP-In)'
        xFirewall AllowFirewallRDPShadowTCPIn
        {
            Name = 'Remote Desktop - Shadow (TCP-In)'
            Ensure = 'Present'
            Enabled = 'True'
        }

        # Enable Firewall Rule 'Remote Desktop - User Mode (TCP-In)'
        xFirewall AllowFirewallRDPUserModeTCPIn
        {
            Name = 'Remote Desktop - User Mode (TCP-In)'
            Ensure = 'Present'
            Enabled = 'True'
        }

        # Enable Firewall Rule 'Remote Desktop - User Mode (UDP-In)'
        xFirewall AllowFirewallRDPUserModeUDPIn
        {
            Name = 'Remote Desktop - User Mode (UDP-In)'
            Ensure = 'Present'
            Enabled = 'True'
        }

Works for 'Remote Desktop - Shadow (TCP-In)' and  'Remote Desktop - User Mode (UDP-In)' but 'Remote Desktop - User Mode (TCP-In)' is created again completely open - Any, any, any regarding ports, programs, protocols, etc!

Set-TargetResource: Applying settings for firewall rule with Name 'Remote Desktop - User Mode (TCP-In)'.
VERBOSE: [MIM01]:                            [[xFirewall]AllowFirewallRDPUserModeTCPIn] Set-TargetResource: Find firewall rule with Name 'Remote Desktop - User Mode (TCP-In)'.
VERBOSE: [MIM01]:                            [[xFirewall]AllowFirewallRDPUserModeTCPIn] Get-FirewallRule: No Firewall Rule found with Name 'Remote Desktop - User Mode (TCP-In)'.
VERBOSE: [MIM01]:                            [[xFirewall]AllowFirewallRDPUserModeTCPIn] Set-TargetResource: We want the firewall rule with Name 'Remote Desktop - User Mode (TCP-In)' to exist since Ensure is set to Present.
VERBOSE: [MIM01]:                            [[xFirewall]AllowFirewallRDPUserModeTCPIn] Set-TargetResource: We want the firewall rule with Name 'Remote Desktop - User Mode (TCP-In)' to exist, but it does not.
VERBOSE: [MIM01]:                            [[xFirewall]AllowFirewallRDPUserModeTCPIn] New-NetFirewallRule DisplayName: Remote Desktop - User Mode (TCP-In)

**Comment by PlagueHO** [comment] 2015-12-25 20:43
I'll take look at this and see if I can figure out what is going on here.

**Comment by PlagueHO** [comment] 2015-12-25 20:49
Oh wait- I've just figured out what is going on here.

You need to set the **name** parameter to be he **name** of the existing rules, rather than the **displayname**.

E.g.
```
    # Enable Firewall Rule 'Remote Desktop - Shadow (TCP-In)'
    xFirewall AllowFirewallRDPShadowTCPIn
    {
        Name = 'RemoteDesktop-Shadow-In-TCP'
        Ensure = 'Present'
        Enabled = 'True'
    }

    # Enable Firewall Rule 'Remote Desktop - User Mode (TCP-In)'
    xFirewall AllowFirewallRDPUserModeTCPIn
    {
        Name = 'RemoteDesktop-UserMode-In-TCP'
        Ensure = 'Present'
        Enabled = 'True'
    }

    # Enable Firewall Rule 'Remote Desktop - User Mode (UDP-In)'
    xFirewall AllowFirewallRDPUserModeUDPIn
    {
        Name = 'RemoteDesktop-UserMode-In-UDP'
        Ensure = 'Present'
        Enabled = 'True'
    }
```

This is because **name** is used as the unique key for the resource, not **displayname**.

Hope that helps! :smile:

**Comment by PlagueHO** [comment] 2015-12-25 20:50
Oh, and easiest way to get the name of the resource is:
```powershell
get-netfirewallrule -DisplayName 'Remote Desktop*'
```

**Comment by Identitry** [comment] 2015-12-25 21:34
Thanks, that explains a lot! :-)
Also, it turns out when enabling remote Desktop from Server manager new Domain,Private rules are created with a Guid as Name. The guids seems to be created on the fly (different between machines) so I guess I have to create duplicate rules in case they've been created already.

**Comment by PlagueHO** [comment] 2015-12-26 00:45
No problem!

Although that is an issue that you've uncovered there with the rules being created with a different GUID when assigned via server manager. I'm assuming this is intended behavior from Server Manager, but it does cause us a problem with using the resource in this way.

A possible solution would be to add a flag to the resource, called something like NameIsDisplayName which when set causes the resource to treat the Name parameter as a DisplayName which would then cause the resource to lookup/update rules using the DisplayName parameter rather than the Name. But I'll wait till @tysonjhayes has a chance to look at this before making and definite plans.

In the meantime, are you possibly able to pop up screenshot or two of these rules with the GUIDs in them (using ```get-netfirewallrule -name <<guid>>```) so I can see if there is anything else that could be used as a key identifier?

Thanks!

**Comment by serbrech** [comment] 2016-05-27 11:14
should this issue be closed?

**Comment by PlagueHO** [comment] 2016-05-27 21:32
Actually yes, I think so. @Identitry - is this something you can close?

**Comment by PlagueHO** [comment] 2016-06-05 00:50
@tysonjhayes - I think we should go ahead and close this one.

**Closed** 2016-06-06 20:12 UTC
